# Baseline Logistic Regression

- **Baseline Logistic Regression**
           - ↓ compare against
- **Weighted Logistic Regression**
- **XGBoost**
- **Isolation Forest**
- **Threshold tuning**

1. Define features and target
2. Split training and test data
3. Train Logistic Regression
4. Make predictions
5. Evaluate fraud detection performance

Dataset
  ↓
Choose X and y
  ↓
Train/test split
  ↓
Preprocessing
  ↓
Create LogisticRegression model
  ↓
model.fit(...)
  ↓
model.predict(...)
  ↓
Confusion matrix / precision / recall / PR-AUC

## Load dataset

In [2]:
import pandas as pd

data_path = "../data/raw/creditcard.csv"
df = pd.read_csv(data_path)

In [4]:
X = df.drop("Class", axis=1)
y = df["Class"]

In [5]:
X.shape, y.shape

((284807, 30), (284807,))

## Split Data

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)# splititng data 80/20%

In [9]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((227845, 30), (56962, 30), (227845,), (56962,))

## feature scaling / standardization

### Create the scaler

In [10]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

In [11]:
scaler.fit(X_train)

StandardScaler()

In [12]:
scaler.mean_

array([ 9.48850937e+04,  7.95290922e-04, -4.81013687e-04, -3.83022392e-04,
       -1.97223997e-05,  1.74584369e-04, -1.17118617e-03,  7.67387574e-05,
       -4.33928397e-04,  7.01756965e-04, -3.89440775e-04, -7.87247374e-04,
        2.71812789e-03, -4.93121683e-04, -5.86174977e-05,  7.44064525e-04,
       -1.06990340e-03,  3.90248279e-04,  5.62369121e-05,  6.63511187e-04,
       -9.98938638e-04,  3.69741873e-04,  3.02706709e-04,  5.03893413e-05,
       -2.77277157e-04, -6.55396231e-04,  1.26095357e-04, -7.04733971e-05,
        1.53721000e-04,  8.81762977e+01])

## Mean, Standard Deviation and variance ofe the Train data

In [13]:
import pandas as pd

scaler_stats = pd.DataFrame({
    "Feature": X_train.columns,
    "Mean": scaler.mean_,
    "Standard Deviation": scaler.scale_,
    "Variance": scaler.var_
})

scaler_stats

   Feature          Mean  Standard Deviation      Variance
0     Time  94885.093704        47488.310822  2.255140e+09
1       V1      0.000795            1.958921  3.837372e+00
2       V2     -0.000481            1.649089  2.719494e+00
3       V3     -0.000383            1.515289  2.296101e+00
4       V4     -0.000020            1.415864  2.004671e+00
5       V5      0.000175            1.379566  1.903203e+00
6       V6     -0.001171            1.331215  1.772133e+00
7       V7      0.000077            1.238428  1.533704e+00
8       V8     -0.000434            1.191479  1.419623e+00
9       V9      0.000702            1.097349  1.204175e+00
10     V10     -0.000389            1.086250  1.179938e+00
11     V11     -0.000787            1.019198  1.038764e+00
12     V12      0.002718            0.996507  9.930258e-01
13     V13     -0.000493            0.994101  9.882362e-01
14     V14     -0.000059            0.955991  9.139189e-01
15     V15      0.000744            0.915141  8.374827e-01
16     V16     -0.001070            0.874241  7.642981e-01
17     V17      0.000390            0.844233  7.127295e-01
18     V18      0.000056            0.838872  7.037061e-01
19     V19      0.000664            0.813929  6.624801e-01
20     V20     -0.000999            0.770804  5.941391e-01
21     V21      0.000370            0.734961  5.401676e-01
22     V22      0.000303            0.725734  5.266897e-01
23     V23      0.000050            0.627417  3.936523e-01
24     V24     -0.000277            0.605320  3.664127e-01
25     V25     -0.000655            0.521235  2.716855e-01
26     V26      0.000126            0.481938  2.322643e-01
27     V27     -0.000070            0.404933  1.639707e-01
28     V28      0.000154            0.326938  1.068888e-01
29  Amount     88.176298          250.722051  6.286155e+04

In [15]:
X_train[["Time", "Amount"]].describe()

                Time         Amount
count  227845.000000  227845.000000
mean    94885.093704      88.176298
std     47488.415034     250.722602
min         0.000000       0.000000
25%     54228.000000       5.640000
50%     84805.000000      22.000000
75%    139364.000000      77.490000
max    172792.000000   25691.160000

In [16]:
# Take one real Amount value from the training data
amount_value = X_train["Amount"].iloc[0]

# Get the learned mean and standard deviation for Amount
amount_mean = scaler.mean_[X_train.columns.get_loc("Amount")]
amount_std = scaler.scale_[X_train.columns.get_loc("Amount")]

# Apply the standardization formula manually
scaled_amount = (amount_value - amount_mean) / amount_std

print("Original Amount:", amount_value)
print("Training Mean:", amount_mean)
print("Training Standard Deviation:", amount_std)
print("Scaled Amount:", scaled_amount)

Original Amount: 7.32
Training Mean: 88.17629770238538
Training Standard Deviation: 250.72205133874502
Scaled Amount: -0.3224937625974599

In [17]:
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [18]:
type(X_train_scaled), X_train_scaled.shape

(numpy.ndarray, (227845, 30))

## Logistic Regression

In [19]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

## Train Model

In [20]:
model.fit(X_train_scaled, y_train)

LogisticRegression()

In [21]:
y_pred = model.predict(X_test_scaled)

In [22]:
y_pred[:20]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
import numpy as np

np.unique(y_pred, return_counts=True)

(array([0, 1]), array([56887,    75]))

In [24]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
cm

array([[56851,    13],
       [   36,    62]])

In [25]:
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred)
precision

0.8266666666666667

In [26]:
from sklearn.metrics import recall_score

recall = recall_score(y_test, y_pred)
recall

0.6326530612244898

In [27]:
from sklearn.metrics import f1_score

f1 = f1_score(y_test, y_pred)
f1

0.7167630057803468

In [28]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
accuracy

0.9991397773954567

Precision = 82.7%
Recall    = 63.3%
F1        = 71.7%
PR-AUC    = next

### PR-AUC.

In [30]:
y_prob = model.predict_proba(X_test_scaled)[:, 1]

In [31]:
y_prob

array([6.66589544e-05, 3.65855417e-05, 6.07869406e-06, ...,
       1.57444971e-05, 6.55799811e-05, 2.65939506e-04], shape=(56962,))

In [32]:
from sklearn.metrics import average_precision_score

pr_auc = average_precision_score(y_test, y_prob)
pr_auc

0.7413820992780461